### PR TITLE
Fix /vendor => /system/vendor => /vendor loop

### PR DESCRIPTION
**Pull request by Flohack74**
for devices with vendor partition.
See rationale at https://gitlab.com/JBBgameich/halium-install/merge_requests/31

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This will require a prerequisite change to some devices, it seems. (darn it)

The Nexus 7, for example, has no `/android/vendor`. This should exist and link to `system/vendor` (note the lack of a leading slash)

**Comment by Flohack74** [comment]
Hmm so how can we find out about this? Just grepping through the fstab when have the system image mounted?

**Comment by Flohack74** [comment]
Can we create this link just additionally, and it will fail on devices that have it, or make it conditonally?

**Comment by UniversalSuperBox** [comment]
We can, but it will need to be added to the pre-start script in lxc-android-config.

**Comment by UniversalSuperBox** [comment]
This has been fixed another way now, correct @Flohack74?

**Comment by Flohack74** [comment]
Yes it was reverted in original halium-install here: https://gitlab.com/JBBgameich/halium-install/-/merge_requests/33

**Pull request closed without merging**
